import ReactQueryProvider from "./_lib/providers/ReactQueryProvider";
import type { Metadata } from "next";
import StyledComponentsRegistry from "./lib/registry";
import ReduxToolkitProvider from "./_lib/providers/ReduxToolkitProvider";
import ThemeProvider from "./_components/themeProvider";

export const metadata: Metadata = {
  title: {
    absolute: "", //ignore template
    default: "Next.js Tutorial - Codevolution",
    template: " %s | Codeevolution", // add suffix
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          margin: 0,
          display: "flex",
          flexDirection: "column",
          minHeight: "100vh",
        }}
      >
        <ReduxToolkitProvider>
          <ReactQueryProvider>
            <StyledComponentsRegistry>
              <header
                style={{
                  width: "100%",
                  backgroundColor: "red",
                  height: "25px",
                }}
              ></header>
              <ThemeProvider>{children}</ThemeProvider>

              <footer
                style={{
                  height: "25px",
                  backgroundColor: "blue",
                  position: "relative",
                  bottom: "0px",
                }}
              ></footer>
            </StyledComponentsRegistry>
          </ReactQueryProvider>
        </ReduxToolkitProvider>
      </body>
    </html>
  );
}
