import type { Metadata } from "next";
import StyledComponentsRegistry from "./lib/registry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          margin: 0,
          display: "flex",
          flexDirection: "column",
          minHeight: "100vh",
        }}
      >
        <header
          style={{
            width: "100%",
            backgroundColor: "red",
            height: "25px",
          }}
        ></header>
        <div
          style={{
            flex: 1,
          }}
        >
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </div>
        <footer
          style={{
            height: "25px",
            backgroundColor: "blue",
            position: "relative",
            bottom: "0px",
          }}
        ></footer>
      </body>
    </html>
  );
}
